@startuml 实训1

actor "患者" as huan
actor "医生" as yi
actor "护士" as hu

(预约就诊) as yuyue
(用电子邮件提醒)
(用电话提醒)
(记录预约就诊记录)
(管理牙科诊所)
(提醒)
(巡诊)

(就诊)


(付款)
(开发票)
(患者付款)
(查询保险)
(记录患者记录)
(记录地址电话号码)


(记录设备使用情况)

hu -- (提醒)
hu -- (管理牙科诊所)
hu -- (查询保险)

(提醒) <.. (用电话提醒) :《extend》
(提醒) <.. (用电子邮件提醒) : 《extend》

yuyue ..> (提醒) :《include》

yi -- (巡诊)

yuyue ..> (记录预约就诊记录) :《include》

(患者付款) ..> (查询保险) : 《extend》
(开发票) ..> (查询保险) : 《extend》

huan -- yuyue
huan -- (付款)
huan -- (就诊)
huan -- (登录)
(登录) <.. (注册) :《include》

(付款) ..> (查询保险) :《include》


(就诊) ..> (记录患者记录) :《include》
(记录地址电话号码) ..> (记录患者记录) : 《extend》

yi -- (记录设备使用情况)
hu -- (记录设备使用情况)
hu -- (记录预约就诊记录)

@enduml