@startuml 实训1

actor "患者" as huan
actor "医生" as yi
actor "护士" as hu

(登录)
(预约)
(就诊)
(记录低耗品和设备使用)
(排班)
(验证有无保险)
(提醒)
(注册)

huan -- (登录)
huan -- (预约)

yi -- (登录)
yi -- (就诊)

hu -- (登录)
hu -- (记录低耗品和设备使用)
hu -- (排班)

(预约) ..> (提醒) :《include》
(登录) <.. (注册) : 《extend》
(就诊) <.. (验证有无保险) : 《extend》

@enduml