@startuml 1_4
class Arthmetic
{
  getResult(numA:float,numB:float):float
}

class Add
{
  +getResult(numA:float,numB:float):float
}

class Del
{
  +getResult(numA:float,numB:float):float
}

class Mul
{
  +getResult(numA:float,numB:float):float
}

class Div
{
  +getResult(numA:float,numB:float):float
}

Arthmetic <|-- Div
Arthmetic <|-- Del
Arthmetic <|-- Add
Arthmetic <|-- Mul



@enduml